name: Build and deploy website

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 12 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build
      uses: adamws/github-pages-generator@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        username: ${{ github.actor }}
        output_dir: ./output
        colorscheme: f0f5f4,00ab91,f0f5f4,0d1117,005182
        ignore_repositories: adamws.github.io,ci-sandbox
        skip_footer: true
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./output
        force_orphan: true
