name: Build and deploy website

on:
  push:
  schedule:
    - cron: "0 12 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'
    - name: Get repositories data
      uses: adamws/github-pages-generator@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        username: ${{ github.actor }}
        output_dir: ./data
        ignore_repositories: adamws,adamws.github.io,ci-sandbox
        data_only: true
    - name: Build
      run: hugo --minify
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./public
        force_orphan: true
