name: Build and deploy website

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 12 * * *"

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      working-directory: ./github-pages-generator
    - name: Build
      run: >
        python build.py --username ${{ github.actor }} --ignore adamws.github.io
        --colorscheme ../colors.json --skip-footer
      working-directory: ./github-pages-generator
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./github-pages-generator/output
        force_orphan: true
